services:
  - type: web
    name: fastapi-contatos
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: MONGODB_URI
        value: sua-string-de-conexao-mongodb
